### ISSUE TITLE
Couldn't show chart when using rtd theme

### ISSUE THREAD

**Issue by shkumagai** [shkumagai/sphinxcontrib.nvd3#1]

**Comment by unixtime** [comment]
I have the same issue with rtd theme. 

Uncaught ReferenceError: nv is not defined
<code>
nv.addGraph(function() {
        var chart = nv.models.multiBarChart();
</code>

**Comment by shkumagai** [comment]
Hi, unixtime. sorry for late response.

This issue caused the rtd theme loads nvd3.js library on a bottom of page.
And it couldn't prevent with specify 'jquery_on_ready' option in same reason.

So, I added new option 'window_onload' and release version 0.1.4.

When you use this extension with the rtd theme, you may add 'window_onload' option to nvd3 directive ;)

Thank you.
