### ISSUE TITLE
Double assignment to `jquery_on_ready`!?

### ISSUE THREAD

**Issue by jhermann** [shkumagai/sphinxcontrib.nvd3#5]
Are these two assignments supposed to be folded into **one** `or` expression?

https://github.com/shkumagai/sphinxcontrib.nvd3/blob/020f81d98083cf3b7e63f2167bcc0138a1df3ddb/src/sphinxcontrib/nvd3/directives.py#L154-L155

**Comment by shkumagai** [comment]
thx. fix it.
